### ISSUE TITLE
404 Error when running script

### ISSUE THREAD

**Issue by b0rr** [beaston02/SMrecorder#2]
Hi. The script worked initially, however I am receiving a 404 error whenever I run it now. 

```
Traceback (most recent call last):
  File "SMrecorder.py", line 112, in <module>
    getOnlineModels()
  File "SMrecorder.py", line 35, in getOnlineModels
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 16
3, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 47
2, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 58
2, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 51
0, in error 
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 44
4, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 59
0, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: File Not Found
```

I'm on mobile so the error might not be complete, but I believe it is correct.

**Comment by beaston02** [comment]
Sorry for the slow reply.

They made some changes to their api. I have updated the script to use the new api URLs.
